/*
Kafka Management API

Kafka Management API is a REST API to manage Kafka instances

API version: 1.16.0
Contact: rhosak-support@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kafkamgmtclient

import (
	"encoding/json"
)

// checks if the MetricsInstantQueryListAllOfItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricsInstantQueryListAllOfItemsInner{}

// MetricsInstantQueryListAllOfItemsInner struct for MetricsInstantQueryListAllOfItemsInner
type MetricsInstantQueryListAllOfItemsInner struct {
	Metric *map[string]string `json:"metric,omitempty"`
	Timestamp *int64 `json:"timestamp,omitempty"`
	Value float64 `json:"value"`
}

// NewMetricsInstantQueryListAllOfItemsInner instantiates a new MetricsInstantQueryListAllOfItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricsInstantQueryListAllOfItemsInner(value float64) *MetricsInstantQueryListAllOfItemsInner {
	this := MetricsInstantQueryListAllOfItemsInner{}
	this.Value = value
	return &this
}

// NewMetricsInstantQueryListAllOfItemsInnerWithDefaults instantiates a new MetricsInstantQueryListAllOfItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsInstantQueryListAllOfItemsInnerWithDefaults() *MetricsInstantQueryListAllOfItemsInner {
	this := MetricsInstantQueryListAllOfItemsInner{}
	return &this
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *MetricsInstantQueryListAllOfItemsInner) GetMetric() map[string]string {
	if o == nil || IsNil(o.Metric) {
		var ret map[string]string
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsInstantQueryListAllOfItemsInner) GetMetricOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *MetricsInstantQueryListAllOfItemsInner) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given map[string]string and assigns it to the Metric field.
func (o *MetricsInstantQueryListAllOfItemsInner) SetMetric(v map[string]string) {
	o.Metric = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *MetricsInstantQueryListAllOfItemsInner) GetTimestamp() int64 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int64
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsInstantQueryListAllOfItemsInner) GetTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *MetricsInstantQueryListAllOfItemsInner) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int64 and assigns it to the Timestamp field.
func (o *MetricsInstantQueryListAllOfItemsInner) SetTimestamp(v int64) {
	o.Timestamp = &v
}

// GetValue returns the Value field value
func (o *MetricsInstantQueryListAllOfItemsInner) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *MetricsInstantQueryListAllOfItemsInner) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *MetricsInstantQueryListAllOfItemsInner) SetValue(v float64) {
	o.Value = v
}

func (o MetricsInstantQueryListAllOfItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricsInstantQueryListAllOfItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableMetricsInstantQueryListAllOfItemsInner struct {
	value *MetricsInstantQueryListAllOfItemsInner
	isSet bool
}

func (v NullableMetricsInstantQueryListAllOfItemsInner) Get() *MetricsInstantQueryListAllOfItemsInner {
	return v.value
}

func (v *NullableMetricsInstantQueryListAllOfItemsInner) Set(val *MetricsInstantQueryListAllOfItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricsInstantQueryListAllOfItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricsInstantQueryListAllOfItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricsInstantQueryListAllOfItemsInner(val *MetricsInstantQueryListAllOfItemsInner) *NullableMetricsInstantQueryListAllOfItemsInner {
	return &NullableMetricsInstantQueryListAllOfItemsInner{value: val, isSet: true}
}

func (v NullableMetricsInstantQueryListAllOfItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricsInstantQueryListAllOfItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


