/*
Kafka Management API

Kafka Management API is a REST API to manage Kafka instances

API version: 1.16.0
Contact: rhosak-support@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kafkamgmtclient

import (
	"encoding/json"
)

// checks if the SupportedKafkaInstanceTypesListAllOfInstanceTypesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportedKafkaInstanceTypesListAllOfInstanceTypesInner{}

// SupportedKafkaInstanceTypesListAllOfInstanceTypesInner struct for SupportedKafkaInstanceTypesListAllOfInstanceTypesInner
type SupportedKafkaInstanceTypesListAllOfInstanceTypesInner struct {
	// Unique identifier of the Kafka instance type.
	Id *string `json:"id,omitempty"`
	// Human readable name of the supported Kafka instance type
	DisplayName *string `json:"display_name,omitempty"`
	// A list of available kafka billing models for the instance type. Each kafka billing model item has a unique 'id'
	SupportedBillingModels []SupportedKafkaBillingModel `json:"supported_billing_models"`
	// A list of Kafka instance sizes available for this instance type
	Sizes []SupportedKafkaInstanceTypeSizesInner `json:"sizes"`
}

// NewSupportedKafkaInstanceTypesListAllOfInstanceTypesInner instantiates a new SupportedKafkaInstanceTypesListAllOfInstanceTypesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedKafkaInstanceTypesListAllOfInstanceTypesInner(supportedBillingModels []SupportedKafkaBillingModel, sizes []SupportedKafkaInstanceTypeSizesInner) *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner {
	this := SupportedKafkaInstanceTypesListAllOfInstanceTypesInner{}
	this.SupportedBillingModels = supportedBillingModels
	this.Sizes = sizes
	return &this
}

// NewSupportedKafkaInstanceTypesListAllOfInstanceTypesInnerWithDefaults instantiates a new SupportedKafkaInstanceTypesListAllOfInstanceTypesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedKafkaInstanceTypesListAllOfInstanceTypesInnerWithDefaults() *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner {
	this := SupportedKafkaInstanceTypesListAllOfInstanceTypesInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) SetId(v string) {
	o.Id = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetSupportedBillingModels returns the SupportedBillingModels field value
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) GetSupportedBillingModels() []SupportedKafkaBillingModel {
	if o == nil {
		var ret []SupportedKafkaBillingModel
		return ret
	}

	return o.SupportedBillingModels
}

// GetSupportedBillingModelsOk returns a tuple with the SupportedBillingModels field value
// and a boolean to check if the value has been set.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) GetSupportedBillingModelsOk() ([]SupportedKafkaBillingModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportedBillingModels, true
}

// SetSupportedBillingModels sets field value
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) SetSupportedBillingModels(v []SupportedKafkaBillingModel) {
	o.SupportedBillingModels = v
}

// GetSizes returns the Sizes field value
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) GetSizes() []SupportedKafkaInstanceTypeSizesInner {
	if o == nil {
		var ret []SupportedKafkaInstanceTypeSizesInner
		return ret
	}

	return o.Sizes
}

// GetSizesOk returns a tuple with the Sizes field value
// and a boolean to check if the value has been set.
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) GetSizesOk() ([]SupportedKafkaInstanceTypeSizesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sizes, true
}

// SetSizes sets field value
func (o *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) SetSizes(v []SupportedKafkaInstanceTypeSizesInner) {
	o.Sizes = v
}

func (o SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	toSerialize["supported_billing_models"] = o.SupportedBillingModels
	toSerialize["sizes"] = o.Sizes
	return toSerialize, nil
}

type NullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner struct {
	value *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner
	isSet bool
}

func (v NullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner) Get() *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner {
	return v.value
}

func (v *NullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner) Set(val *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner(val *SupportedKafkaInstanceTypesListAllOfInstanceTypesInner) *NullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner {
	return &NullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner{value: val, isSet: true}
}

func (v NullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedKafkaInstanceTypesListAllOfInstanceTypesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


