/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the AccountGroupRequestAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountGroupRequestAllOf{}

// AccountGroupRequestAllOf struct for AccountGroupRequestAllOf
type AccountGroupRequestAllOf struct {
	Description string `json:"description"`
	Name string `json:"name"`
}

// NewAccountGroupRequestAllOf instantiates a new AccountGroupRequestAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountGroupRequestAllOf(description string, name string) *AccountGroupRequestAllOf {
	this := AccountGroupRequestAllOf{}
	this.Description = description
	this.Name = name
	return &this
}

// NewAccountGroupRequestAllOfWithDefaults instantiates a new AccountGroupRequestAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountGroupRequestAllOfWithDefaults() *AccountGroupRequestAllOf {
	this := AccountGroupRequestAllOf{}
	return &this
}

// GetDescription returns the Description field value
func (o *AccountGroupRequestAllOf) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AccountGroupRequestAllOf) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AccountGroupRequestAllOf) SetDescription(v string) {
	o.Description = v
}

// GetName returns the Name field value
func (o *AccountGroupRequestAllOf) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AccountGroupRequestAllOf) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AccountGroupRequestAllOf) SetName(v string) {
	o.Name = v
}

func (o AccountGroupRequestAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountGroupRequestAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableAccountGroupRequestAllOf struct {
	value *AccountGroupRequestAllOf
	isSet bool
}

func (v NullableAccountGroupRequestAllOf) Get() *AccountGroupRequestAllOf {
	return v.value
}

func (v *NullableAccountGroupRequestAllOf) Set(val *AccountGroupRequestAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountGroupRequestAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountGroupRequestAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountGroupRequestAllOf(val *AccountGroupRequestAllOf) *NullableAccountGroupRequestAllOf {
	return &NullableAccountGroupRequestAllOf{value: val, isSet: true}
}

func (v NullableAccountGroupRequestAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountGroupRequestAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


