/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the OrganizationListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationListAllOf{}

// OrganizationListAllOf struct for OrganizationListAllOf
type OrganizationListAllOf struct {
	Items []Organization `json:"items,omitempty"`
}

// NewOrganizationListAllOf instantiates a new OrganizationListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationListAllOf() *OrganizationListAllOf {
	this := OrganizationListAllOf{}
	return &this
}

// NewOrganizationListAllOfWithDefaults instantiates a new OrganizationListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationListAllOfWithDefaults() *OrganizationListAllOf {
	this := OrganizationListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *OrganizationListAllOf) GetItems() []Organization {
	if o == nil || IsNil(o.Items) {
		var ret []Organization
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOf) GetItemsOk() ([]Organization, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *OrganizationListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Organization and assigns it to the Items field.
func (o *OrganizationListAllOf) SetItems(v []Organization) {
	o.Items = v
}

func (o OrganizationListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableOrganizationListAllOf struct {
	value *OrganizationListAllOf
	isSet bool
}

func (v NullableOrganizationListAllOf) Get() *OrganizationListAllOf {
	return v.value
}

func (v *NullableOrganizationListAllOf) Set(val *OrganizationListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationListAllOf(val *OrganizationListAllOf) *NullableOrganizationListAllOf {
	return &NullableOrganizationListAllOf{value: val, isSet: true}
}

func (v NullableOrganizationListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


