/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the SkuRulesAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkuRulesAllOf{}

// SkuRulesAllOf struct for SkuRulesAllOf
type SkuRulesAllOf struct {
	Allowed *int32 `json:"allowed,omitempty"`
	QuotaId *string `json:"quota_id,omitempty"`
	Sku *string `json:"sku,omitempty"`
}

// NewSkuRulesAllOf instantiates a new SkuRulesAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkuRulesAllOf() *SkuRulesAllOf {
	this := SkuRulesAllOf{}
	return &this
}

// NewSkuRulesAllOfWithDefaults instantiates a new SkuRulesAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkuRulesAllOfWithDefaults() *SkuRulesAllOf {
	this := SkuRulesAllOf{}
	return &this
}

// GetAllowed returns the Allowed field value if set, zero value otherwise.
func (o *SkuRulesAllOf) GetAllowed() int32 {
	if o == nil || IsNil(o.Allowed) {
		var ret int32
		return ret
	}
	return *o.Allowed
}

// GetAllowedOk returns a tuple with the Allowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuRulesAllOf) GetAllowedOk() (*int32, bool) {
	if o == nil || IsNil(o.Allowed) {
		return nil, false
	}
	return o.Allowed, true
}

// HasAllowed returns a boolean if a field has been set.
func (o *SkuRulesAllOf) HasAllowed() bool {
	if o != nil && !IsNil(o.Allowed) {
		return true
	}

	return false
}

// SetAllowed gets a reference to the given int32 and assigns it to the Allowed field.
func (o *SkuRulesAllOf) SetAllowed(v int32) {
	o.Allowed = &v
}

// GetQuotaId returns the QuotaId field value if set, zero value otherwise.
func (o *SkuRulesAllOf) GetQuotaId() string {
	if o == nil || IsNil(o.QuotaId) {
		var ret string
		return ret
	}
	return *o.QuotaId
}

// GetQuotaIdOk returns a tuple with the QuotaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuRulesAllOf) GetQuotaIdOk() (*string, bool) {
	if o == nil || IsNil(o.QuotaId) {
		return nil, false
	}
	return o.QuotaId, true
}

// HasQuotaId returns a boolean if a field has been set.
func (o *SkuRulesAllOf) HasQuotaId() bool {
	if o != nil && !IsNil(o.QuotaId) {
		return true
	}

	return false
}

// SetQuotaId gets a reference to the given string and assigns it to the QuotaId field.
func (o *SkuRulesAllOf) SetQuotaId(v string) {
	o.QuotaId = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *SkuRulesAllOf) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuRulesAllOf) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *SkuRulesAllOf) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *SkuRulesAllOf) SetSku(v string) {
	o.Sku = &v
}

func (o SkuRulesAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkuRulesAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Allowed) {
		toSerialize["allowed"] = o.Allowed
	}
	if !IsNil(o.QuotaId) {
		toSerialize["quota_id"] = o.QuotaId
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	return toSerialize, nil
}

type NullableSkuRulesAllOf struct {
	value *SkuRulesAllOf
	isSet bool
}

func (v NullableSkuRulesAllOf) Get() *SkuRulesAllOf {
	return v.value
}

func (v *NullableSkuRulesAllOf) Set(val *SkuRulesAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSkuRulesAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSkuRulesAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkuRulesAllOf(val *SkuRulesAllOf) *NullableSkuRulesAllOf {
	return &NullableSkuRulesAllOf{value: val, isSet: true}
}

func (v NullableSkuRulesAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkuRulesAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


