/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
	"time"
)

// checks if the AccountGroupListAllOfItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountGroupListAllOfItemsInner{}

// AccountGroupListAllOfItemsInner struct for AccountGroupListAllOfItemsInner
type AccountGroupListAllOfItemsInner struct {
	Href *string `json:"href,omitempty"`
	Id *string `json:"id,omitempty"`
	Kind *string `json:"kind,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Description string `json:"description"`
	ManagedBy string `json:"managed_by"`
	Name string `json:"name"`
	OrganizationId string `json:"organization_id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewAccountGroupListAllOfItemsInner instantiates a new AccountGroupListAllOfItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountGroupListAllOfItemsInner(description string, managedBy string, name string, organizationId string) *AccountGroupListAllOfItemsInner {
	this := AccountGroupListAllOfItemsInner{}
	this.Description = description
	this.ManagedBy = managedBy
	this.Name = name
	this.OrganizationId = organizationId
	return &this
}

// NewAccountGroupListAllOfItemsInnerWithDefaults instantiates a new AccountGroupListAllOfItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountGroupListAllOfItemsInnerWithDefaults() *AccountGroupListAllOfItemsInner {
	this := AccountGroupListAllOfItemsInner{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *AccountGroupListAllOfItemsInner) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupListAllOfItemsInner) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *AccountGroupListAllOfItemsInner) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *AccountGroupListAllOfItemsInner) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AccountGroupListAllOfItemsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupListAllOfItemsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AccountGroupListAllOfItemsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AccountGroupListAllOfItemsInner) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *AccountGroupListAllOfItemsInner) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupListAllOfItemsInner) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *AccountGroupListAllOfItemsInner) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *AccountGroupListAllOfItemsInner) SetKind(v string) {
	o.Kind = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AccountGroupListAllOfItemsInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupListAllOfItemsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AccountGroupListAllOfItemsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AccountGroupListAllOfItemsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetDescription returns the Description field value
func (o *AccountGroupListAllOfItemsInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AccountGroupListAllOfItemsInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AccountGroupListAllOfItemsInner) SetDescription(v string) {
	o.Description = v
}

// GetManagedBy returns the ManagedBy field value
func (o *AccountGroupListAllOfItemsInner) GetManagedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManagedBy
}

// GetManagedByOk returns a tuple with the ManagedBy field value
// and a boolean to check if the value has been set.
func (o *AccountGroupListAllOfItemsInner) GetManagedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManagedBy, true
}

// SetManagedBy sets field value
func (o *AccountGroupListAllOfItemsInner) SetManagedBy(v string) {
	o.ManagedBy = v
}

// GetName returns the Name field value
func (o *AccountGroupListAllOfItemsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AccountGroupListAllOfItemsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AccountGroupListAllOfItemsInner) SetName(v string) {
	o.Name = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *AccountGroupListAllOfItemsInner) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *AccountGroupListAllOfItemsInner) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *AccountGroupListAllOfItemsInner) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AccountGroupListAllOfItemsInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupListAllOfItemsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AccountGroupListAllOfItemsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *AccountGroupListAllOfItemsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o AccountGroupListAllOfItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountGroupListAllOfItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	toSerialize["description"] = o.Description
	toSerialize["managed_by"] = o.ManagedBy
	toSerialize["name"] = o.Name
	toSerialize["organization_id"] = o.OrganizationId
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableAccountGroupListAllOfItemsInner struct {
	value *AccountGroupListAllOfItemsInner
	isSet bool
}

func (v NullableAccountGroupListAllOfItemsInner) Get() *AccountGroupListAllOfItemsInner {
	return v.value
}

func (v *NullableAccountGroupListAllOfItemsInner) Set(val *AccountGroupListAllOfItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountGroupListAllOfItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountGroupListAllOfItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountGroupListAllOfItemsInner(val *AccountGroupListAllOfItemsInner) *NullableAccountGroupListAllOfItemsInner {
	return &NullableAccountGroupListAllOfItemsInner{value: val, isSet: true}
}

func (v NullableAccountGroupListAllOfItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountGroupListAllOfItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


