/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the ClusterAuthorizationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterAuthorizationRequest{}

// ClusterAuthorizationRequest struct for ClusterAuthorizationRequest
type ClusterAuthorizationRequest struct {
	AccountUsername string `json:"account_username"`
	AvailabilityZone *string `json:"availability_zone,omitempty"`
	Byoc *bool `json:"byoc,omitempty"`
	CloudAccountId *string `json:"cloud_account_id,omitempty"`
	CloudProviderId *string `json:"cloud_provider_id,omitempty"`
	ClusterId string `json:"cluster_id"`
	Disconnected *bool `json:"disconnected,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	ExternalClusterId *string `json:"external_cluster_id,omitempty"`
	Managed *bool `json:"managed,omitempty"`
	ProductCategory *string `json:"product_category,omitempty"`
	ProductId *string `json:"product_id,omitempty"`
	QuotaVersion *string `json:"quota_version,omitempty"`
	Reserve *bool `json:"reserve,omitempty"`
	Resources []ReservedResource `json:"resources,omitempty"`
}

// NewClusterAuthorizationRequest instantiates a new ClusterAuthorizationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterAuthorizationRequest(accountUsername string, clusterId string) *ClusterAuthorizationRequest {
	this := ClusterAuthorizationRequest{}
	this.AccountUsername = accountUsername
	this.ClusterId = clusterId
	var productId string = "osd"
	this.ProductId = &productId
	return &this
}

// NewClusterAuthorizationRequestWithDefaults instantiates a new ClusterAuthorizationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterAuthorizationRequestWithDefaults() *ClusterAuthorizationRequest {
	this := ClusterAuthorizationRequest{}
	var productId string = "osd"
	this.ProductId = &productId
	return &this
}

// GetAccountUsername returns the AccountUsername field value
func (o *ClusterAuthorizationRequest) GetAccountUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountUsername
}

// GetAccountUsernameOk returns a tuple with the AccountUsername field value
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetAccountUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountUsername, true
}

// SetAccountUsername sets field value
func (o *ClusterAuthorizationRequest) SetAccountUsername(v string) {
	o.AccountUsername = v
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetAvailabilityZone() string {
	if o == nil || IsNil(o.AvailabilityZone) {
		var ret string
		return ret
	}
	return *o.AvailabilityZone
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetAvailabilityZoneOk() (*string, bool) {
	if o == nil || IsNil(o.AvailabilityZone) {
		return nil, false
	}
	return o.AvailabilityZone, true
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasAvailabilityZone() bool {
	if o != nil && !IsNil(o.AvailabilityZone) {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given string and assigns it to the AvailabilityZone field.
func (o *ClusterAuthorizationRequest) SetAvailabilityZone(v string) {
	o.AvailabilityZone = &v
}

// GetByoc returns the Byoc field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetByoc() bool {
	if o == nil || IsNil(o.Byoc) {
		var ret bool
		return ret
	}
	return *o.Byoc
}

// GetByocOk returns a tuple with the Byoc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetByocOk() (*bool, bool) {
	if o == nil || IsNil(o.Byoc) {
		return nil, false
	}
	return o.Byoc, true
}

// HasByoc returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasByoc() bool {
	if o != nil && !IsNil(o.Byoc) {
		return true
	}

	return false
}

// SetByoc gets a reference to the given bool and assigns it to the Byoc field.
func (o *ClusterAuthorizationRequest) SetByoc(v bool) {
	o.Byoc = &v
}

// GetCloudAccountId returns the CloudAccountId field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetCloudAccountId() string {
	if o == nil || IsNil(o.CloudAccountId) {
		var ret string
		return ret
	}
	return *o.CloudAccountId
}

// GetCloudAccountIdOk returns a tuple with the CloudAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetCloudAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.CloudAccountId) {
		return nil, false
	}
	return o.CloudAccountId, true
}

// HasCloudAccountId returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasCloudAccountId() bool {
	if o != nil && !IsNil(o.CloudAccountId) {
		return true
	}

	return false
}

// SetCloudAccountId gets a reference to the given string and assigns it to the CloudAccountId field.
func (o *ClusterAuthorizationRequest) SetCloudAccountId(v string) {
	o.CloudAccountId = &v
}

// GetCloudProviderId returns the CloudProviderId field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetCloudProviderId() string {
	if o == nil || IsNil(o.CloudProviderId) {
		var ret string
		return ret
	}
	return *o.CloudProviderId
}

// GetCloudProviderIdOk returns a tuple with the CloudProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetCloudProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.CloudProviderId) {
		return nil, false
	}
	return o.CloudProviderId, true
}

// HasCloudProviderId returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasCloudProviderId() bool {
	if o != nil && !IsNil(o.CloudProviderId) {
		return true
	}

	return false
}

// SetCloudProviderId gets a reference to the given string and assigns it to the CloudProviderId field.
func (o *ClusterAuthorizationRequest) SetCloudProviderId(v string) {
	o.CloudProviderId = &v
}

// GetClusterId returns the ClusterId field value
func (o *ClusterAuthorizationRequest) GetClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterId, true
}

// SetClusterId sets field value
func (o *ClusterAuthorizationRequest) SetClusterId(v string) {
	o.ClusterId = v
}

// GetDisconnected returns the Disconnected field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetDisconnected() bool {
	if o == nil || IsNil(o.Disconnected) {
		var ret bool
		return ret
	}
	return *o.Disconnected
}

// GetDisconnectedOk returns a tuple with the Disconnected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetDisconnectedOk() (*bool, bool) {
	if o == nil || IsNil(o.Disconnected) {
		return nil, false
	}
	return o.Disconnected, true
}

// HasDisconnected returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasDisconnected() bool {
	if o != nil && !IsNil(o.Disconnected) {
		return true
	}

	return false
}

// SetDisconnected gets a reference to the given bool and assigns it to the Disconnected field.
func (o *ClusterAuthorizationRequest) SetDisconnected(v bool) {
	o.Disconnected = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ClusterAuthorizationRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetExternalClusterId returns the ExternalClusterId field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetExternalClusterId() string {
	if o == nil || IsNil(o.ExternalClusterId) {
		var ret string
		return ret
	}
	return *o.ExternalClusterId
}

// GetExternalClusterIdOk returns a tuple with the ExternalClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetExternalClusterIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalClusterId) {
		return nil, false
	}
	return o.ExternalClusterId, true
}

// HasExternalClusterId returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasExternalClusterId() bool {
	if o != nil && !IsNil(o.ExternalClusterId) {
		return true
	}

	return false
}

// SetExternalClusterId gets a reference to the given string and assigns it to the ExternalClusterId field.
func (o *ClusterAuthorizationRequest) SetExternalClusterId(v string) {
	o.ExternalClusterId = &v
}

// GetManaged returns the Managed field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetManaged() bool {
	if o == nil || IsNil(o.Managed) {
		var ret bool
		return ret
	}
	return *o.Managed
}

// GetManagedOk returns a tuple with the Managed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetManagedOk() (*bool, bool) {
	if o == nil || IsNil(o.Managed) {
		return nil, false
	}
	return o.Managed, true
}

// HasManaged returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasManaged() bool {
	if o != nil && !IsNil(o.Managed) {
		return true
	}

	return false
}

// SetManaged gets a reference to the given bool and assigns it to the Managed field.
func (o *ClusterAuthorizationRequest) SetManaged(v bool) {
	o.Managed = &v
}

// GetProductCategory returns the ProductCategory field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetProductCategory() string {
	if o == nil || IsNil(o.ProductCategory) {
		var ret string
		return ret
	}
	return *o.ProductCategory
}

// GetProductCategoryOk returns a tuple with the ProductCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetProductCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.ProductCategory) {
		return nil, false
	}
	return o.ProductCategory, true
}

// HasProductCategory returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasProductCategory() bool {
	if o != nil && !IsNil(o.ProductCategory) {
		return true
	}

	return false
}

// SetProductCategory gets a reference to the given string and assigns it to the ProductCategory field.
func (o *ClusterAuthorizationRequest) SetProductCategory(v string) {
	o.ProductCategory = &v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetProductId() string {
	if o == nil || IsNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *ClusterAuthorizationRequest) SetProductId(v string) {
	o.ProductId = &v
}

// GetQuotaVersion returns the QuotaVersion field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetQuotaVersion() string {
	if o == nil || IsNil(o.QuotaVersion) {
		var ret string
		return ret
	}
	return *o.QuotaVersion
}

// GetQuotaVersionOk returns a tuple with the QuotaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetQuotaVersionOk() (*string, bool) {
	if o == nil || IsNil(o.QuotaVersion) {
		return nil, false
	}
	return o.QuotaVersion, true
}

// HasQuotaVersion returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasQuotaVersion() bool {
	if o != nil && !IsNil(o.QuotaVersion) {
		return true
	}

	return false
}

// SetQuotaVersion gets a reference to the given string and assigns it to the QuotaVersion field.
func (o *ClusterAuthorizationRequest) SetQuotaVersion(v string) {
	o.QuotaVersion = &v
}

// GetReserve returns the Reserve field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetReserve() bool {
	if o == nil || IsNil(o.Reserve) {
		var ret bool
		return ret
	}
	return *o.Reserve
}

// GetReserveOk returns a tuple with the Reserve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetReserveOk() (*bool, bool) {
	if o == nil || IsNil(o.Reserve) {
		return nil, false
	}
	return o.Reserve, true
}

// HasReserve returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasReserve() bool {
	if o != nil && !IsNil(o.Reserve) {
		return true
	}

	return false
}

// SetReserve gets a reference to the given bool and assigns it to the Reserve field.
func (o *ClusterAuthorizationRequest) SetReserve(v bool) {
	o.Reserve = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *ClusterAuthorizationRequest) GetResources() []ReservedResource {
	if o == nil || IsNil(o.Resources) {
		var ret []ReservedResource
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAuthorizationRequest) GetResourcesOk() ([]ReservedResource, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *ClusterAuthorizationRequest) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given []ReservedResource and assigns it to the Resources field.
func (o *ClusterAuthorizationRequest) SetResources(v []ReservedResource) {
	o.Resources = v
}

func (o ClusterAuthorizationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterAuthorizationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_username"] = o.AccountUsername
	if !IsNil(o.AvailabilityZone) {
		toSerialize["availability_zone"] = o.AvailabilityZone
	}
	if !IsNil(o.Byoc) {
		toSerialize["byoc"] = o.Byoc
	}
	if !IsNil(o.CloudAccountId) {
		toSerialize["cloud_account_id"] = o.CloudAccountId
	}
	if !IsNil(o.CloudProviderId) {
		toSerialize["cloud_provider_id"] = o.CloudProviderId
	}
	toSerialize["cluster_id"] = o.ClusterId
	if !IsNil(o.Disconnected) {
		toSerialize["disconnected"] = o.Disconnected
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.ExternalClusterId) {
		toSerialize["external_cluster_id"] = o.ExternalClusterId
	}
	if !IsNil(o.Managed) {
		toSerialize["managed"] = o.Managed
	}
	if !IsNil(o.ProductCategory) {
		toSerialize["product_category"] = o.ProductCategory
	}
	if !IsNil(o.ProductId) {
		toSerialize["product_id"] = o.ProductId
	}
	if !IsNil(o.QuotaVersion) {
		toSerialize["quota_version"] = o.QuotaVersion
	}
	if !IsNil(o.Reserve) {
		toSerialize["reserve"] = o.Reserve
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	return toSerialize, nil
}

type NullableClusterAuthorizationRequest struct {
	value *ClusterAuthorizationRequest
	isSet bool
}

func (v NullableClusterAuthorizationRequest) Get() *ClusterAuthorizationRequest {
	return v.value
}

func (v *NullableClusterAuthorizationRequest) Set(val *ClusterAuthorizationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterAuthorizationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterAuthorizationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterAuthorizationRequest(val *ClusterAuthorizationRequest) *NullableClusterAuthorizationRequest {
	return &NullableClusterAuthorizationRequest{value: val, isSet: true}
}

func (v NullableClusterAuthorizationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterAuthorizationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


