/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the ClusterTransferRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterTransferRequest{}

// ClusterTransferRequest struct for ClusterTransferRequest
type ClusterTransferRequest struct {
	ClusterUuid *string `json:"cluster_uuid,omitempty"`
	Owner *string `json:"owner,omitempty"`
	Recipient *string `json:"recipient,omitempty"`
}

// NewClusterTransferRequest instantiates a new ClusterTransferRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterTransferRequest() *ClusterTransferRequest {
	this := ClusterTransferRequest{}
	return &this
}

// NewClusterTransferRequestWithDefaults instantiates a new ClusterTransferRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterTransferRequestWithDefaults() *ClusterTransferRequest {
	this := ClusterTransferRequest{}
	return &this
}

// GetClusterUuid returns the ClusterUuid field value if set, zero value otherwise.
func (o *ClusterTransferRequest) GetClusterUuid() string {
	if o == nil || IsNil(o.ClusterUuid) {
		var ret string
		return ret
	}
	return *o.ClusterUuid
}

// GetClusterUuidOk returns a tuple with the ClusterUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterTransferRequest) GetClusterUuidOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterUuid) {
		return nil, false
	}
	return o.ClusterUuid, true
}

// HasClusterUuid returns a boolean if a field has been set.
func (o *ClusterTransferRequest) HasClusterUuid() bool {
	if o != nil && !IsNil(o.ClusterUuid) {
		return true
	}

	return false
}

// SetClusterUuid gets a reference to the given string and assigns it to the ClusterUuid field.
func (o *ClusterTransferRequest) SetClusterUuid(v string) {
	o.ClusterUuid = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *ClusterTransferRequest) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterTransferRequest) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *ClusterTransferRequest) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *ClusterTransferRequest) SetOwner(v string) {
	o.Owner = &v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *ClusterTransferRequest) GetRecipient() string {
	if o == nil || IsNil(o.Recipient) {
		var ret string
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterTransferRequest) GetRecipientOk() (*string, bool) {
	if o == nil || IsNil(o.Recipient) {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *ClusterTransferRequest) HasRecipient() bool {
	if o != nil && !IsNil(o.Recipient) {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given string and assigns it to the Recipient field.
func (o *ClusterTransferRequest) SetRecipient(v string) {
	o.Recipient = &v
}

func (o ClusterTransferRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterTransferRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClusterUuid) {
		toSerialize["cluster_uuid"] = o.ClusterUuid
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Recipient) {
		toSerialize["recipient"] = o.Recipient
	}
	return toSerialize, nil
}

type NullableClusterTransferRequest struct {
	value *ClusterTransferRequest
	isSet bool
}

func (v NullableClusterTransferRequest) Get() *ClusterTransferRequest {
	return v.value
}

func (v *NullableClusterTransferRequest) Set(val *ClusterTransferRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterTransferRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterTransferRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterTransferRequest(val *ClusterTransferRequest) *NullableClusterTransferRequest {
	return &NullableClusterTransferRequest{value: val, isSet: true}
}

func (v NullableClusterTransferRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterTransferRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


