/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the LandingPageCTLItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LandingPageCTLItem{}

// LandingPageCTLItem struct for LandingPageCTLItem
type LandingPageCTLItem struct {
	Shape *LandingPageCTLItemShape `json:"shape,omitempty"`
}

// NewLandingPageCTLItem instantiates a new LandingPageCTLItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLandingPageCTLItem() *LandingPageCTLItem {
	this := LandingPageCTLItem{}
	return &this
}

// NewLandingPageCTLItemWithDefaults instantiates a new LandingPageCTLItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLandingPageCTLItemWithDefaults() *LandingPageCTLItem {
	this := LandingPageCTLItem{}
	return &this
}

// GetShape returns the Shape field value if set, zero value otherwise.
func (o *LandingPageCTLItem) GetShape() LandingPageCTLItemShape {
	if o == nil || IsNil(o.Shape) {
		var ret LandingPageCTLItemShape
		return ret
	}
	return *o.Shape
}

// GetShapeOk returns a tuple with the Shape field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LandingPageCTLItem) GetShapeOk() (*LandingPageCTLItemShape, bool) {
	if o == nil || IsNil(o.Shape) {
		return nil, false
	}
	return o.Shape, true
}

// HasShape returns a boolean if a field has been set.
func (o *LandingPageCTLItem) HasShape() bool {
	if o != nil && !IsNil(o.Shape) {
		return true
	}

	return false
}

// SetShape gets a reference to the given LandingPageCTLItemShape and assigns it to the Shape field.
func (o *LandingPageCTLItem) SetShape(v LandingPageCTLItemShape) {
	o.Shape = &v
}

func (o LandingPageCTLItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LandingPageCTLItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Shape) {
		toSerialize["shape"] = o.Shape
	}
	return toSerialize, nil
}

type NullableLandingPageCTLItem struct {
	value *LandingPageCTLItem
	isSet bool
}

func (v NullableLandingPageCTLItem) Get() *LandingPageCTLItem {
	return v.value
}

func (v *NullableLandingPageCTLItem) Set(val *LandingPageCTLItem) {
	v.value = val
	v.isSet = true
}

func (v NullableLandingPageCTLItem) IsSet() bool {
	return v.isSet
}

func (v *NullableLandingPageCTLItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLandingPageCTLItem(val *LandingPageCTLItem) *NullableLandingPageCTLItem {
	return &NullableLandingPageCTLItem{value: val, isSet: true}
}

func (v NullableLandingPageCTLItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLandingPageCTLItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


