/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
	"time"
)

// checks if the OrganizationListAllOfItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationListAllOfItemsInner{}

// OrganizationListAllOfItemsInner struct for OrganizationListAllOfItemsInner
type OrganizationListAllOfItemsInner struct {
	Href *string `json:"href,omitempty"`
	Id *string `json:"id,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Capabilities []Capability `json:"capabilities,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	EbsAccountId *string `json:"ebs_account_id,omitempty"`
	ExternalId *string `json:"external_id,omitempty"`
	Labels []Label `json:"labels,omitempty"`
	Name *string `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewOrganizationListAllOfItemsInner instantiates a new OrganizationListAllOfItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationListAllOfItemsInner() *OrganizationListAllOfItemsInner {
	this := OrganizationListAllOfItemsInner{}
	return &this
}

// NewOrganizationListAllOfItemsInnerWithDefaults instantiates a new OrganizationListAllOfItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationListAllOfItemsInnerWithDefaults() *OrganizationListAllOfItemsInner {
	this := OrganizationListAllOfItemsInner{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *OrganizationListAllOfItemsInner) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OrganizationListAllOfItemsInner) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *OrganizationListAllOfItemsInner) SetKind(v string) {
	o.Kind = &v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetCapabilities() []Capability {
	if o == nil || IsNil(o.Capabilities) {
		var ret []Capability
		return ret
	}
	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetCapabilitiesOk() ([]Capability, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given []Capability and assigns it to the Capabilities field.
func (o *OrganizationListAllOfItemsInner) SetCapabilities(v []Capability) {
	o.Capabilities = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *OrganizationListAllOfItemsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetEbsAccountId returns the EbsAccountId field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetEbsAccountId() string {
	if o == nil || IsNil(o.EbsAccountId) {
		var ret string
		return ret
	}
	return *o.EbsAccountId
}

// GetEbsAccountIdOk returns a tuple with the EbsAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetEbsAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.EbsAccountId) {
		return nil, false
	}
	return o.EbsAccountId, true
}

// HasEbsAccountId returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasEbsAccountId() bool {
	if o != nil && !IsNil(o.EbsAccountId) {
		return true
	}

	return false
}

// SetEbsAccountId gets a reference to the given string and assigns it to the EbsAccountId field.
func (o *OrganizationListAllOfItemsInner) SetEbsAccountId(v string) {
	o.EbsAccountId = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *OrganizationListAllOfItemsInner) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetLabels() []Label {
	if o == nil || IsNil(o.Labels) {
		var ret []Label
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetLabelsOk() ([]Label, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []Label and assigns it to the Labels field.
func (o *OrganizationListAllOfItemsInner) SetLabels(v []Label) {
	o.Labels = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrganizationListAllOfItemsInner) SetName(v string) {
	o.Name = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *OrganizationListAllOfItemsInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationListAllOfItemsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *OrganizationListAllOfItemsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *OrganizationListAllOfItemsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o OrganizationListAllOfItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationListAllOfItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Capabilities) {
		toSerialize["capabilities"] = o.Capabilities
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.EbsAccountId) {
		toSerialize["ebs_account_id"] = o.EbsAccountId
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableOrganizationListAllOfItemsInner struct {
	value *OrganizationListAllOfItemsInner
	isSet bool
}

func (v NullableOrganizationListAllOfItemsInner) Get() *OrganizationListAllOfItemsInner {
	return v.value
}

func (v *NullableOrganizationListAllOfItemsInner) Set(val *OrganizationListAllOfItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationListAllOfItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationListAllOfItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationListAllOfItemsInner(val *OrganizationListAllOfItemsInner) *NullableOrganizationListAllOfItemsInner {
	return &NullableOrganizationListAllOfItemsInner{value: val, isSet: true}
}

func (v NullableOrganizationListAllOfItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationListAllOfItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


