/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the CloudResourceListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudResourceListAllOf{}

// CloudResourceListAllOf struct for CloudResourceListAllOf
type CloudResourceListAllOf struct {
	Items []CloudResource `json:"items,omitempty"`
}

// NewCloudResourceListAllOf instantiates a new CloudResourceListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudResourceListAllOf() *CloudResourceListAllOf {
	this := CloudResourceListAllOf{}
	return &this
}

// NewCloudResourceListAllOfWithDefaults instantiates a new CloudResourceListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudResourceListAllOfWithDefaults() *CloudResourceListAllOf {
	this := CloudResourceListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CloudResourceListAllOf) GetItems() []CloudResource {
	if o == nil || IsNil(o.Items) {
		var ret []CloudResource
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudResourceListAllOf) GetItemsOk() ([]CloudResource, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CloudResourceListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CloudResource and assigns it to the Items field.
func (o *CloudResourceListAllOf) SetItems(v []CloudResource) {
	o.Items = v
}

func (o CloudResourceListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudResourceListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCloudResourceListAllOf struct {
	value *CloudResourceListAllOf
	isSet bool
}

func (v NullableCloudResourceListAllOf) Get() *CloudResourceListAllOf {
	return v.value
}

func (v *NullableCloudResourceListAllOf) Set(val *CloudResourceListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudResourceListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudResourceListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudResourceListAllOf(val *CloudResourceListAllOf) *NullableCloudResourceListAllOf {
	return &NullableCloudResourceListAllOf{value: val, isSet: true}
}

func (v NullableCloudResourceListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudResourceListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


