/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the ResourceQuotaListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceQuotaListAllOf{}

// ResourceQuotaListAllOf struct for ResourceQuotaListAllOf
type ResourceQuotaListAllOf struct {
	Items []ResourceQuota `json:"items,omitempty"`
}

// NewResourceQuotaListAllOf instantiates a new ResourceQuotaListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceQuotaListAllOf() *ResourceQuotaListAllOf {
	this := ResourceQuotaListAllOf{}
	return &this
}

// NewResourceQuotaListAllOfWithDefaults instantiates a new ResourceQuotaListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceQuotaListAllOfWithDefaults() *ResourceQuotaListAllOf {
	this := ResourceQuotaListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ResourceQuotaListAllOf) GetItems() []ResourceQuota {
	if o == nil || IsNil(o.Items) {
		var ret []ResourceQuota
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceQuotaListAllOf) GetItemsOk() ([]ResourceQuota, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ResourceQuotaListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ResourceQuota and assigns it to the Items field.
func (o *ResourceQuotaListAllOf) SetItems(v []ResourceQuota) {
	o.Items = v
}

func (o ResourceQuotaListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceQuotaListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableResourceQuotaListAllOf struct {
	value *ResourceQuotaListAllOf
	isSet bool
}

func (v NullableResourceQuotaListAllOf) Get() *ResourceQuotaListAllOf {
	return v.value
}

func (v *NullableResourceQuotaListAllOf) Set(val *ResourceQuotaListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceQuotaListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceQuotaListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceQuotaListAllOf(val *ResourceQuotaListAllOf) *NullableResourceQuotaListAllOf {
	return &NullableResourceQuotaListAllOf{value: val, isSet: true}
}

func (v NullableResourceQuotaListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceQuotaListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


