/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the QuotaRulesListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotaRulesListAllOf{}

// QuotaRulesListAllOf struct for QuotaRulesListAllOf
type QuotaRulesListAllOf struct {
	Items []QuotaRules `json:"items,omitempty"`
}

// NewQuotaRulesListAllOf instantiates a new QuotaRulesListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaRulesListAllOf() *QuotaRulesListAllOf {
	this := QuotaRulesListAllOf{}
	return &this
}

// NewQuotaRulesListAllOfWithDefaults instantiates a new QuotaRulesListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaRulesListAllOfWithDefaults() *QuotaRulesListAllOf {
	this := QuotaRulesListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *QuotaRulesListAllOf) GetItems() []QuotaRules {
	if o == nil || IsNil(o.Items) {
		var ret []QuotaRules
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaRulesListAllOf) GetItemsOk() ([]QuotaRules, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *QuotaRulesListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []QuotaRules and assigns it to the Items field.
func (o *QuotaRulesListAllOf) SetItems(v []QuotaRules) {
	o.Items = v
}

func (o QuotaRulesListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotaRulesListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableQuotaRulesListAllOf struct {
	value *QuotaRulesListAllOf
	isSet bool
}

func (v NullableQuotaRulesListAllOf) Get() *QuotaRulesListAllOf {
	return v.value
}

func (v *NullableQuotaRulesListAllOf) Set(val *QuotaRulesListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaRulesListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaRulesListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaRulesListAllOf(val *QuotaRulesListAllOf) *NullableQuotaRulesListAllOf {
	return &NullableQuotaRulesListAllOf{value: val, isSet: true}
}

func (v NullableQuotaRulesListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaRulesListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


