/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
	"time"
)

// checks if the AccountGroupAssignmentListAllOfItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountGroupAssignmentListAllOfItemsInner{}

// AccountGroupAssignmentListAllOfItemsInner struct for AccountGroupAssignmentListAllOfItemsInner
type AccountGroupAssignmentListAllOfItemsInner struct {
	Href *string `json:"href,omitempty"`
	Id *string `json:"id,omitempty"`
	Kind *string `json:"kind,omitempty"`
	AccountGroupId string `json:"account_group_id"`
	AccountId string `json:"account_id"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewAccountGroupAssignmentListAllOfItemsInner instantiates a new AccountGroupAssignmentListAllOfItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountGroupAssignmentListAllOfItemsInner(accountGroupId string, accountId string) *AccountGroupAssignmentListAllOfItemsInner {
	this := AccountGroupAssignmentListAllOfItemsInner{}
	this.AccountGroupId = accountGroupId
	this.AccountId = accountId
	return &this
}

// NewAccountGroupAssignmentListAllOfItemsInnerWithDefaults instantiates a new AccountGroupAssignmentListAllOfItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountGroupAssignmentListAllOfItemsInnerWithDefaults() *AccountGroupAssignmentListAllOfItemsInner {
	this := AccountGroupAssignmentListAllOfItemsInner{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *AccountGroupAssignmentListAllOfItemsInner) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AccountGroupAssignmentListAllOfItemsInner) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *AccountGroupAssignmentListAllOfItemsInner) SetKind(v string) {
	o.Kind = &v
}

// GetAccountGroupId returns the AccountGroupId field value
func (o *AccountGroupAssignmentListAllOfItemsInner) GetAccountGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountGroupId
}

// GetAccountGroupIdOk returns a tuple with the AccountGroupId field value
// and a boolean to check if the value has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetAccountGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountGroupId, true
}

// SetAccountGroupId sets field value
func (o *AccountGroupAssignmentListAllOfItemsInner) SetAccountGroupId(v string) {
	o.AccountGroupId = v
}

// GetAccountId returns the AccountId field value
func (o *AccountGroupAssignmentListAllOfItemsInner) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AccountGroupAssignmentListAllOfItemsInner) SetAccountId(v string) {
	o.AccountId = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AccountGroupAssignmentListAllOfItemsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AccountGroupAssignmentListAllOfItemsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *AccountGroupAssignmentListAllOfItemsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o AccountGroupAssignmentListAllOfItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountGroupAssignmentListAllOfItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	toSerialize["account_group_id"] = o.AccountGroupId
	toSerialize["account_id"] = o.AccountId
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableAccountGroupAssignmentListAllOfItemsInner struct {
	value *AccountGroupAssignmentListAllOfItemsInner
	isSet bool
}

func (v NullableAccountGroupAssignmentListAllOfItemsInner) Get() *AccountGroupAssignmentListAllOfItemsInner {
	return v.value
}

func (v *NullableAccountGroupAssignmentListAllOfItemsInner) Set(val *AccountGroupAssignmentListAllOfItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountGroupAssignmentListAllOfItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountGroupAssignmentListAllOfItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountGroupAssignmentListAllOfItemsInner(val *AccountGroupAssignmentListAllOfItemsInner) *NullableAccountGroupAssignmentListAllOfItemsInner {
	return &NullableAccountGroupAssignmentListAllOfItemsInner{value: val, isSet: true}
}

func (v NullableAccountGroupAssignmentListAllOfItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountGroupAssignmentListAllOfItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


