/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the RegistryListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistryListAllOf{}

// RegistryListAllOf struct for RegistryListAllOf
type RegistryListAllOf struct {
	Items []Registry `json:"items,omitempty"`
}

// NewRegistryListAllOf instantiates a new RegistryListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryListAllOf() *RegistryListAllOf {
	this := RegistryListAllOf{}
	return &this
}

// NewRegistryListAllOfWithDefaults instantiates a new RegistryListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryListAllOfWithDefaults() *RegistryListAllOf {
	this := RegistryListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *RegistryListAllOf) GetItems() []Registry {
	if o == nil || IsNil(o.Items) {
		var ret []Registry
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryListAllOf) GetItemsOk() ([]Registry, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *RegistryListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Registry and assigns it to the Items field.
func (o *RegistryListAllOf) SetItems(v []Registry) {
	o.Items = v
}

func (o RegistryListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistryListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableRegistryListAllOf struct {
	value *RegistryListAllOf
	isSet bool
}

func (v NullableRegistryListAllOf) Get() *RegistryListAllOf {
	return v.value
}

func (v *NullableRegistryListAllOf) Set(val *RegistryListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryListAllOf(val *RegistryListAllOf) *NullableRegistryListAllOf {
	return &NullableRegistryListAllOf{value: val, isSet: true}
}

func (v NullableRegistryListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


