/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the ConsumedQuotaListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumedQuotaListAllOf{}

// ConsumedQuotaListAllOf struct for ConsumedQuotaListAllOf
type ConsumedQuotaListAllOf struct {
	Items []ConsumedQuota `json:"items,omitempty"`
}

// NewConsumedQuotaListAllOf instantiates a new ConsumedQuotaListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumedQuotaListAllOf() *ConsumedQuotaListAllOf {
	this := ConsumedQuotaListAllOf{}
	return &this
}

// NewConsumedQuotaListAllOfWithDefaults instantiates a new ConsumedQuotaListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumedQuotaListAllOfWithDefaults() *ConsumedQuotaListAllOf {
	this := ConsumedQuotaListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ConsumedQuotaListAllOf) GetItems() []ConsumedQuota {
	if o == nil || IsNil(o.Items) {
		var ret []ConsumedQuota
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumedQuotaListAllOf) GetItemsOk() ([]ConsumedQuota, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ConsumedQuotaListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ConsumedQuota and assigns it to the Items field.
func (o *ConsumedQuotaListAllOf) SetItems(v []ConsumedQuota) {
	o.Items = v
}

func (o ConsumedQuotaListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumedQuotaListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableConsumedQuotaListAllOf struct {
	value *ConsumedQuotaListAllOf
	isSet bool
}

func (v NullableConsumedQuotaListAllOf) Get() *ConsumedQuotaListAllOf {
	return v.value
}

func (v *NullableConsumedQuotaListAllOf) Set(val *ConsumedQuotaListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumedQuotaListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumedQuotaListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumedQuotaListAllOf(val *ConsumedQuotaListAllOf) *NullableConsumedQuotaListAllOf {
	return &NullableConsumedQuotaListAllOf{value: val, isSet: true}
}

func (v NullableConsumedQuotaListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumedQuotaListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


