/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the NotificationContactCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationContactCreateRequest{}

// NotificationContactCreateRequest struct for NotificationContactCreateRequest
type NotificationContactCreateRequest struct {
	AccountIdentifier *string `json:"account_identifier,omitempty"`
}

// NewNotificationContactCreateRequest instantiates a new NotificationContactCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationContactCreateRequest() *NotificationContactCreateRequest {
	this := NotificationContactCreateRequest{}
	return &this
}

// NewNotificationContactCreateRequestWithDefaults instantiates a new NotificationContactCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationContactCreateRequestWithDefaults() *NotificationContactCreateRequest {
	this := NotificationContactCreateRequest{}
	return &this
}

// GetAccountIdentifier returns the AccountIdentifier field value if set, zero value otherwise.
func (o *NotificationContactCreateRequest) GetAccountIdentifier() string {
	if o == nil || IsNil(o.AccountIdentifier) {
		var ret string
		return ret
	}
	return *o.AccountIdentifier
}

// GetAccountIdentifierOk returns a tuple with the AccountIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationContactCreateRequest) GetAccountIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.AccountIdentifier) {
		return nil, false
	}
	return o.AccountIdentifier, true
}

// HasAccountIdentifier returns a boolean if a field has been set.
func (o *NotificationContactCreateRequest) HasAccountIdentifier() bool {
	if o != nil && !IsNil(o.AccountIdentifier) {
		return true
	}

	return false
}

// SetAccountIdentifier gets a reference to the given string and assigns it to the AccountIdentifier field.
func (o *NotificationContactCreateRequest) SetAccountIdentifier(v string) {
	o.AccountIdentifier = &v
}

func (o NotificationContactCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationContactCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountIdentifier) {
		toSerialize["account_identifier"] = o.AccountIdentifier
	}
	return toSerialize, nil
}

type NullableNotificationContactCreateRequest struct {
	value *NotificationContactCreateRequest
	isSet bool
}

func (v NullableNotificationContactCreateRequest) Get() *NotificationContactCreateRequest {
	return v.value
}

func (v *NullableNotificationContactCreateRequest) Set(val *NotificationContactCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationContactCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationContactCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationContactCreateRequest(val *NotificationContactCreateRequest) *NullableNotificationContactCreateRequest {
	return &NullableNotificationContactCreateRequest{value: val, isSet: true}
}

func (v NullableNotificationContactCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationContactCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


