/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the AccountGroupAssignmentListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountGroupAssignmentListAllOf{}

// AccountGroupAssignmentListAllOf struct for AccountGroupAssignmentListAllOf
type AccountGroupAssignmentListAllOf struct {
	Items []AccountGroupAssignmentListAllOfItemsInner `json:"items,omitempty"`
}

// NewAccountGroupAssignmentListAllOf instantiates a new AccountGroupAssignmentListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountGroupAssignmentListAllOf() *AccountGroupAssignmentListAllOf {
	this := AccountGroupAssignmentListAllOf{}
	return &this
}

// NewAccountGroupAssignmentListAllOfWithDefaults instantiates a new AccountGroupAssignmentListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountGroupAssignmentListAllOfWithDefaults() *AccountGroupAssignmentListAllOf {
	this := AccountGroupAssignmentListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *AccountGroupAssignmentListAllOf) GetItems() []AccountGroupAssignmentListAllOfItemsInner {
	if o == nil || IsNil(o.Items) {
		var ret []AccountGroupAssignmentListAllOfItemsInner
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupAssignmentListAllOf) GetItemsOk() ([]AccountGroupAssignmentListAllOfItemsInner, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *AccountGroupAssignmentListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []AccountGroupAssignmentListAllOfItemsInner and assigns it to the Items field.
func (o *AccountGroupAssignmentListAllOf) SetItems(v []AccountGroupAssignmentListAllOfItemsInner) {
	o.Items = v
}

func (o AccountGroupAssignmentListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountGroupAssignmentListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableAccountGroupAssignmentListAllOf struct {
	value *AccountGroupAssignmentListAllOf
	isSet bool
}

func (v NullableAccountGroupAssignmentListAllOf) Get() *AccountGroupAssignmentListAllOf {
	return v.value
}

func (v *NullableAccountGroupAssignmentListAllOf) Set(val *AccountGroupAssignmentListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountGroupAssignmentListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountGroupAssignmentListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountGroupAssignmentListAllOf(val *AccountGroupAssignmentListAllOf) *NullableAccountGroupAssignmentListAllOf {
	return &NullableAccountGroupAssignmentListAllOf{value: val, isSet: true}
}

func (v NullableAccountGroupAssignmentListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountGroupAssignmentListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


