/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the RegistryCredentialListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistryCredentialListAllOf{}

// RegistryCredentialListAllOf struct for RegistryCredentialListAllOf
type RegistryCredentialListAllOf struct {
	Items []RegistryCredential `json:"items,omitempty"`
}

// NewRegistryCredentialListAllOf instantiates a new RegistryCredentialListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryCredentialListAllOf() *RegistryCredentialListAllOf {
	this := RegistryCredentialListAllOf{}
	return &this
}

// NewRegistryCredentialListAllOfWithDefaults instantiates a new RegistryCredentialListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryCredentialListAllOfWithDefaults() *RegistryCredentialListAllOf {
	this := RegistryCredentialListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *RegistryCredentialListAllOf) GetItems() []RegistryCredential {
	if o == nil || IsNil(o.Items) {
		var ret []RegistryCredential
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryCredentialListAllOf) GetItemsOk() ([]RegistryCredential, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *RegistryCredentialListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []RegistryCredential and assigns it to the Items field.
func (o *RegistryCredentialListAllOf) SetItems(v []RegistryCredential) {
	o.Items = v
}

func (o RegistryCredentialListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistryCredentialListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableRegistryCredentialListAllOf struct {
	value *RegistryCredentialListAllOf
	isSet bool
}

func (v NullableRegistryCredentialListAllOf) Get() *RegistryCredentialListAllOf {
	return v.value
}

func (v *NullableRegistryCredentialListAllOf) Set(val *RegistryCredentialListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryCredentialListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryCredentialListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryCredentialListAllOf(val *RegistryCredentialListAllOf) *NullableRegistryCredentialListAllOf {
	return &NullableRegistryCredentialListAllOf{value: val, isSet: true}
}

func (v NullableRegistryCredentialListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryCredentialListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


