/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the AccountListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountListAllOf{}

// AccountListAllOf struct for AccountListAllOf
type AccountListAllOf struct {
	Items []Account `json:"items,omitempty"`
}

// NewAccountListAllOf instantiates a new AccountListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountListAllOf() *AccountListAllOf {
	this := AccountListAllOf{}
	return &this
}

// NewAccountListAllOfWithDefaults instantiates a new AccountListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountListAllOfWithDefaults() *AccountListAllOf {
	this := AccountListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *AccountListAllOf) GetItems() []Account {
	if o == nil || IsNil(o.Items) {
		var ret []Account
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountListAllOf) GetItemsOk() ([]Account, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *AccountListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Account and assigns it to the Items field.
func (o *AccountListAllOf) SetItems(v []Account) {
	o.Items = v
}

func (o AccountListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableAccountListAllOf struct {
	value *AccountListAllOf
	isSet bool
}

func (v NullableAccountListAllOf) Get() *AccountListAllOf {
	return v.value
}

func (v *NullableAccountListAllOf) Set(val *AccountListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountListAllOf(val *AccountListAllOf) *NullableAccountListAllOf {
	return &NullableAccountListAllOf{value: val, isSet: true}
}

func (v NullableAccountListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


