/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accountmgmtclient

import (
	"encoding/json"
)

// checks if the QuotaRulesAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotaRulesAllOf{}

// QuotaRulesAllOf struct for QuotaRulesAllOf
type QuotaRulesAllOf struct {
	AvailabilityZone *string `json:"availability_zone,omitempty"`
	BillingModel *string `json:"billing_model,omitempty"`
	Byoc *string `json:"byoc,omitempty"`
	Cloud *string `json:"cloud,omitempty"`
	Cost int32 `json:"cost"`
	Name *string `json:"name,omitempty"`
	Product *string `json:"product,omitempty"`
	QuotaId *string `json:"quota_id,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewQuotaRulesAllOf instantiates a new QuotaRulesAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaRulesAllOf(cost int32) *QuotaRulesAllOf {
	this := QuotaRulesAllOf{}
	this.Cost = cost
	return &this
}

// NewQuotaRulesAllOfWithDefaults instantiates a new QuotaRulesAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaRulesAllOfWithDefaults() *QuotaRulesAllOf {
	this := QuotaRulesAllOf{}
	return &this
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise.
func (o *QuotaRulesAllOf) GetAvailabilityZone() string {
	if o == nil || IsNil(o.AvailabilityZone) {
		var ret string
		return ret
	}
	return *o.AvailabilityZone
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaRulesAllOf) GetAvailabilityZoneOk() (*string, bool) {
	if o == nil || IsNil(o.AvailabilityZone) {
		return nil, false
	}
	return o.AvailabilityZone, true
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *QuotaRulesAllOf) HasAvailabilityZone() bool {
	if o != nil && !IsNil(o.AvailabilityZone) {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given string and assigns it to the AvailabilityZone field.
func (o *QuotaRulesAllOf) SetAvailabilityZone(v string) {
	o.AvailabilityZone = &v
}

// GetBillingModel returns the BillingModel field value if set, zero value otherwise.
func (o *QuotaRulesAllOf) GetBillingModel() string {
	if o == nil || IsNil(o.BillingModel) {
		var ret string
		return ret
	}
	return *o.BillingModel
}

// GetBillingModelOk returns a tuple with the BillingModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaRulesAllOf) GetBillingModelOk() (*string, bool) {
	if o == nil || IsNil(o.BillingModel) {
		return nil, false
	}
	return o.BillingModel, true
}

// HasBillingModel returns a boolean if a field has been set.
func (o *QuotaRulesAllOf) HasBillingModel() bool {
	if o != nil && !IsNil(o.BillingModel) {
		return true
	}

	return false
}

// SetBillingModel gets a reference to the given string and assigns it to the BillingModel field.
func (o *QuotaRulesAllOf) SetBillingModel(v string) {
	o.BillingModel = &v
}

// GetByoc returns the Byoc field value if set, zero value otherwise.
func (o *QuotaRulesAllOf) GetByoc() string {
	if o == nil || IsNil(o.Byoc) {
		var ret string
		return ret
	}
	return *o.Byoc
}

// GetByocOk returns a tuple with the Byoc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaRulesAllOf) GetByocOk() (*string, bool) {
	if o == nil || IsNil(o.Byoc) {
		return nil, false
	}
	return o.Byoc, true
}

// HasByoc returns a boolean if a field has been set.
func (o *QuotaRulesAllOf) HasByoc() bool {
	if o != nil && !IsNil(o.Byoc) {
		return true
	}

	return false
}

// SetByoc gets a reference to the given string and assigns it to the Byoc field.
func (o *QuotaRulesAllOf) SetByoc(v string) {
	o.Byoc = &v
}

// GetCloud returns the Cloud field value if set, zero value otherwise.
func (o *QuotaRulesAllOf) GetCloud() string {
	if o == nil || IsNil(o.Cloud) {
		var ret string
		return ret
	}
	return *o.Cloud
}

// GetCloudOk returns a tuple with the Cloud field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaRulesAllOf) GetCloudOk() (*string, bool) {
	if o == nil || IsNil(o.Cloud) {
		return nil, false
	}
	return o.Cloud, true
}

// HasCloud returns a boolean if a field has been set.
func (o *QuotaRulesAllOf) HasCloud() bool {
	if o != nil && !IsNil(o.Cloud) {
		return true
	}

	return false
}

// SetCloud gets a reference to the given string and assigns it to the Cloud field.
func (o *QuotaRulesAllOf) SetCloud(v string) {
	o.Cloud = &v
}

// GetCost returns the Cost field value
func (o *QuotaRulesAllOf) GetCost() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Cost
}

// GetCostOk returns a tuple with the Cost field value
// and a boolean to check if the value has been set.
func (o *QuotaRulesAllOf) GetCostOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cost, true
}

// SetCost sets field value
func (o *QuotaRulesAllOf) SetCost(v int32) {
	o.Cost = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *QuotaRulesAllOf) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaRulesAllOf) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *QuotaRulesAllOf) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *QuotaRulesAllOf) SetName(v string) {
	o.Name = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *QuotaRulesAllOf) GetProduct() string {
	if o == nil || IsNil(o.Product) {
		var ret string
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaRulesAllOf) GetProductOk() (*string, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *QuotaRulesAllOf) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given string and assigns it to the Product field.
func (o *QuotaRulesAllOf) SetProduct(v string) {
	o.Product = &v
}

// GetQuotaId returns the QuotaId field value if set, zero value otherwise.
func (o *QuotaRulesAllOf) GetQuotaId() string {
	if o == nil || IsNil(o.QuotaId) {
		var ret string
		return ret
	}
	return *o.QuotaId
}

// GetQuotaIdOk returns a tuple with the QuotaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaRulesAllOf) GetQuotaIdOk() (*string, bool) {
	if o == nil || IsNil(o.QuotaId) {
		return nil, false
	}
	return o.QuotaId, true
}

// HasQuotaId returns a boolean if a field has been set.
func (o *QuotaRulesAllOf) HasQuotaId() bool {
	if o != nil && !IsNil(o.QuotaId) {
		return true
	}

	return false
}

// SetQuotaId gets a reference to the given string and assigns it to the QuotaId field.
func (o *QuotaRulesAllOf) SetQuotaId(v string) {
	o.QuotaId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *QuotaRulesAllOf) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaRulesAllOf) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *QuotaRulesAllOf) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *QuotaRulesAllOf) SetType(v string) {
	o.Type = &v
}

func (o QuotaRulesAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotaRulesAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailabilityZone) {
		toSerialize["availability_zone"] = o.AvailabilityZone
	}
	if !IsNil(o.BillingModel) {
		toSerialize["billing_model"] = o.BillingModel
	}
	if !IsNil(o.Byoc) {
		toSerialize["byoc"] = o.Byoc
	}
	if !IsNil(o.Cloud) {
		toSerialize["cloud"] = o.Cloud
	}
	toSerialize["cost"] = o.Cost
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if !IsNil(o.QuotaId) {
		toSerialize["quota_id"] = o.QuotaId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableQuotaRulesAllOf struct {
	value *QuotaRulesAllOf
	isSet bool
}

func (v NullableQuotaRulesAllOf) Get() *QuotaRulesAllOf {
	return v.value
}

func (v *NullableQuotaRulesAllOf) Set(val *QuotaRulesAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaRulesAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaRulesAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaRulesAllOf(val *QuotaRulesAllOf) *NullableQuotaRulesAllOf {
	return &NullableQuotaRulesAllOf{value: val, isSet: true}
}

func (v NullableQuotaRulesAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaRulesAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


