/*
sso.redhat.com API documentation

This is the API documentation for sso.redhat.com

API version: 5.0.19-SNAPSHOT
Contact: it-user-team-list@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package serviceaccountsclient

import (
	"encoding/json"
)

// checks if the ServiceAccountCreateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountCreateRequestData{}

// ServiceAccountCreateRequestData struct for ServiceAccountCreateRequestData
type ServiceAccountCreateRequestData struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
}

// NewServiceAccountCreateRequestData instantiates a new ServiceAccountCreateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountCreateRequestData(name string) *ServiceAccountCreateRequestData {
	this := ServiceAccountCreateRequestData{}
	this.Name = name
	return &this
}

// NewServiceAccountCreateRequestDataWithDefaults instantiates a new ServiceAccountCreateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountCreateRequestDataWithDefaults() *ServiceAccountCreateRequestData {
	this := ServiceAccountCreateRequestData{}
	return &this
}

// GetName returns the Name field value
func (o *ServiceAccountCreateRequestData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceAccountCreateRequestData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceAccountCreateRequestData) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServiceAccountCreateRequestData) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountCreateRequestData) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServiceAccountCreateRequestData) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServiceAccountCreateRequestData) SetDescription(v string) {
	o.Description = &v
}

func (o ServiceAccountCreateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountCreateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableServiceAccountCreateRequestData struct {
	value *ServiceAccountCreateRequestData
	isSet bool
}

func (v NullableServiceAccountCreateRequestData) Get() *ServiceAccountCreateRequestData {
	return v.value
}

func (v *NullableServiceAccountCreateRequestData) Set(val *ServiceAccountCreateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountCreateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountCreateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountCreateRequestData(val *ServiceAccountCreateRequestData) *NullableServiceAccountCreateRequestData {
	return &NullableServiceAccountCreateRequestData{value: val, isSet: true}
}

func (v NullableServiceAccountCreateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountCreateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


