name: Update API specs 
on:
  repository_dispatch:
    types: openapi-spec-change
  schedule:
    - cron: '0 0 * * *'
  ## Manual request that can be used for testing and retriggering failed updates
  workflow_dispatch:
jobs:
  generate_api_specs:
    env:
      APP_SERVICES_TOKEN: ${{ secrets.APP_SERVICES_TOKEN }}
      BF2_TOKEN: ${{ secrets.BF2_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install jq
        run: sudo apt-get install jq
      - name: Fetch OpenAPI doc
        run: python scripts/fetch_api.py
  start-generate-sdks-workflow:
    needs: generate_api_specs # these 'need' fields are used to keep jobs running in order
    uses: ./.github/workflows/generate-sdks.yaml
  start-generate-errors-workflow:
    needs: start-generate-sdks-workflow 
    uses: ./.github/workflows/generate-errors.yaml
  make-pull-request:
    needs: start-generate-errors-workflow 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/create-pull-request@v4
        name: Make pull request
        with:
          title: "chore(all): re-generate SDKs"
          token: "${{ secrets.CI_USER_TOKEN }}"
          commit-message: "chore(all): re-generate OpenAPI client(s)"
          author: "app-services-ci <app-services-ci@users.noreply.github.com>"
          branch: chore/generate-sdks
          branch-suffix: timestamp
          reviewers: '@redhat-developer/app-services-sdk-maintainers'
          delete-branch: true
          body: |
            _This pull request was auto-generated_
            This PR adds the latest generated SDK changes.